# Generated by Django 4.2.17 on 2025-01-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='deck_list',
            new_name='deck_content',
        ),
    ]
